name: Metrics
on:
  schedule:
    - cron: "0 */24 * * *"
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          
          base: header, repositories
          
          plugin_traffic: yes
          
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          
          plugin_notable: yes
          plugin_notable_types: commit, pull_request, issue
